apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "handyman-admin.fullname" . }}
  labels:
    {{- include "handyman-admin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "handyman-admin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-config.yaml") . | sha256sum | trunc 10}}
      labels:
        {{- include "handyman-admin.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "handyman-admin.fullname" . }}-conf
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "handyman-admin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-dns-resolver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "janeczku/go-dnsmasq:release-1.0.7"
          args:
            - --listen
            - "127.0.0.1:53"
            - --default-resolver
            - -search
        - name: {{ .Chart.Name }}
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
